export const hotelCategories = [
  { name: "All", count: 6, active: true },
  { name: "5 Star", count: 1, active: false },
  { name: "Luxury", count: 2, active: false },
  { name: "Resorts", count: 1, active: false },
  { name: "Apartments", count: 2, active: false },
];

import { hotelDadou, hotelDadouFacilities1, hotelDadouFacilities2, hotelDadouFacilities3, hotelDadouFacilities4, hotelDadouFacilities5, hotelDadouHero, hotelDadouLocation, hotelDadouRooms1, hotelDadouRooms2, hotelDadouRooms3, hotelDadouRooms4, hotelDadouRooms5, hotelDadouSlider1, hotelDadouSlider2, hotelDadouSlider3, hotelDadouSlider4, hotelKeppler, hotelKepplerFacilities1, hotelKepplerFacilities2, hotelKepplerFacilities3, hotelKepplerFacilities4, hotelKepplerFacilities5, hotelKepplerHero, hotelKepplerLocation, hotelKepplerRooms1, hotelKepplerRooms2, hotelKepplerRooms3, hotelKepplerRooms4, hotelKepplerRooms5, hotelKepplerSlider1, hotelKepplerSlider2, hotelKepplerSlider3, hotelKepplerSlider4, hotelKepplerSlider5, hotelKepplerSlider6, hotelPadam, hotelPadamFacilities1, hotelPadamFacilities2, hotelPadamFacilities3, hotelPadamHero, hotelPadamLocation, hotelPadamRooms1, hotelPadamRooms2, hotelPadamRooms3, hotelPadamSlider1, hotelPadamSlider2, hotelPadamSlider3, hotelPadamSlider4, hotelPastel, hotelPastelFacilities1, hotelPastelFacilities2, hotelPastelFacilities3, hotelPastelHero, hotelPastelLocation, hotelPastelRooms1, hotelPastelRooms2, hotelPastelRooms3, hotelPastelSlider1, hotelPastelSlider2, hotelPastelSlider3, hotelPastelSlider4, hotelVictorHugoKleber, hotelVictorHugoKleberFacilities1, hotelVictorHugoKleberFacilities2, hotelVictorHugoKleberFacilities3, hotelVictorHugoKleberFacilities4, hotelVictorHugoKleberHero, hotelVictorHugoKleberLocation, hotelVictorHugoKleberRooms1, hotelVictorHugoKleberRooms2, hotelVictorHugoKleberRooms3, hotelVictorHugoKleberRooms4, hotelVictorHugoKleberSlider1, hotelVictorHugoKleberSlider2, hotelVictorHugoKleberSlider3, hotelVictorHugoKleberSlider4, hotelVictorHugoKleberSlider5, laDemeureMontaigne, laDemeureMontaigneFacilities1, laDemeureMontaigneFacilities2, laDemeureMontaigneFacilities3, laDemeureMontaigneFacilities4, laDemeureMontaigneFacilities5, laDemeureMontaigneHero, laDemeureMontaigneLocation, laDemeureMontaigneRooms1, laDemeureMontaigneRooms2, laDemeureMontaigneRooms3, laDemeureMontaigneRooms4, laDemeureMontaigneRooms5, laDemeureMontaigneSlider1, laDemeureMontaigneSlider2, laDemeureMontaigneSlider3, laDemeureMontaigneSlider4, laDemeureMontaigneSlider5, monsieurGeorges, monsieurGeorgesFacilities1, monsieurGeorgesFacilities2, monsieurGeorgesFacilities3, monsieurGeorgesFacilities4, monsieurGeorgesHero, monsieurGeorgesLocation, monsieurGeorgesRooms1, monsieurGeorgesRooms2, monsieurGeorgesRooms3, monsieurGeorgesRooms4, monsieurGeorgesSlider1, monsieurGeorgesSlider2, monsieurGeorgesSlider3, monsieurGeorgesSlider4 } from "../assets/hotelImages";

export const hotelDetails = [
  {
    id: 1,
    hotelName: "Monsieur Georges",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "17 rue Washington 75008 Paris",
    address: "17 rue Washington 75008 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://monsieurgeorge.com/",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      monsieurGeorgesFacilities1,
      monsieurGeorgesFacilities2,
      monsieurGeorgesFacilities3,
      monsieurGeorgesFacilities4,
    ],
    rooms: [
      monsieurGeorgesRooms1,
      monsieurGeorgesRooms2,
      monsieurGeorgesRooms3,
      monsieurGeorgesRooms4,
    ],
    slider: [
      monsieurGeorgesSlider1,
      monsieurGeorgesSlider2,
      monsieurGeorgesSlider3,
      monsieurGeorgesSlider4,
    ],
    category: "Luxury",
    price: 75.90,
    banner: monsieurGeorges,
    heroImage: monsieurGeorgesHero,
    locationImage: monsieurGeorgesLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d656.0543753765472!2d2.3024321!3d48.8731301!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fc1ec4e3729%3A0xe6b164a2d37bcfe3!2s17%20Rue%20Washington%2C%2075008%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745062143701!5m2!1sen!2s",
    // addressURL: "https://www.google.com/maps/place/17+Rue+Washington,+75008+Paris,+France/@48.8731301,2.3024321,19.33z/data=!4m6!3m5!1s0x47e66fc1ec4e3729:0xe6b164a2d37bcfe3!8m2!3d48.8730276!4d2.3025216!16s%2Fg%2F11c43v7pb8?authuser=0&entry=ttu&g_ep=EgoyMDI1MDQxNC4xIKXMDSoASAFQAw%3D%3D"
  },
  {
    id: 2,
    hotelName: "Hotel Pastel",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "79 rue Lauriston 75116 Paris",
    address: "79 rue Lauriston 75116 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://hotelpastelparis.com",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      hotelPastelFacilities1,
      hotelPastelFacilities2,
      hotelPastelFacilities3,
    ],
    rooms: [
      hotelPastelRooms1,
      hotelPastelRooms2,
      hotelPastelRooms3,
    ],
    slider: [
      hotelPastelSlider1,
      hotelPastelSlider2,
      hotelPastelSlider3,
      hotelPastelSlider4,
    ],
    category: "5 Star",
    price: 75.90,
    banner: hotelPastel,
    heroImage: hotelPastelHero,
    locationImage: hotelPastelLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d656.116507958991!2d2.2891492!3d48.8683918!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66ff01dd67683%3A0x2ca49de2437f6d0a!2s79%20Rue%20Lauriston%2C%2075116%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745062239626!5m2!1sen!2s"
  },
  {
    id: 3,
    hotelName: "La Demeure Montaigne",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "18, rue Clément Marot 75008 Paris",
    address: "18, rue Clément Marot 75008 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://www.lademeuremontaigne.com",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      laDemeureMontaigneFacilities1,
      laDemeureMontaigneFacilities2,
      laDemeureMontaigneFacilities3,
      laDemeureMontaigneFacilities4,
      laDemeureMontaigneFacilities5,
    ],
    rooms: [
      laDemeureMontaigneRooms1,
      laDemeureMontaigneRooms2,
      laDemeureMontaigneRooms3,
      laDemeureMontaigneRooms4,
      laDemeureMontaigneRooms5,
    ],
    slider: [
      laDemeureMontaigneSlider1,
      laDemeureMontaigneSlider2,
      laDemeureMontaigneSlider3,
      laDemeureMontaigneSlider4,
      laDemeureMontaigneSlider5,
    ],
    category: "Luxury",
    price: 75.90,
    banner: laDemeureMontaigne,
    heroImage: laDemeureMontaigneHero,
    locationImage: laDemeureMontaigneLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d656.1219941567618!2d2.303199!3d48.8679734!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fc327c53bdd%3A0x8716c83a89f0908a!2s18%20Rue%20Cl%C3%A9ment%20Marot%2C%2075008%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745062423823!5m2!1sen!2s"
  },
  {
    id: 4,
    //addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d164.0282668166093!2d2.2979819!3d48.8686542!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fe85f01688d%3A0xdca6da21d8d476bc!2s9%20Rue%20Jean%20Giraudoux%2C%2075116%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745057880490!5m2!1sen!2s",
    hotelName: "Hotel Padam",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "9 rue Jean-Giraudoux 75016 Paris",
    address: "9 rue Jean-Giraudoux 75016 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://www.padam-hotel.com",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      hotelPadamFacilities1,
      hotelPadamFacilities2,
      hotelPadamFacilities3,
    ],
    rooms: [
      hotelPadamRooms1,
      hotelPadamRooms2,
      hotelPadamRooms3,
    ],
    slider: [
      hotelPadamSlider1,
      hotelPadamSlider2,
      hotelPadamSlider3,
      hotelPadamSlider4,
    ],
    category: "Resorts",
    price: 75.90,
    banner: hotelPadam,
    heroImage: hotelPadamHero,
    locationImage: hotelPadamLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d164.0282668166093!2d2.2979819!3d48.8686542!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fe85f01688d%3A0xdca6da21d8d476bc!2s9%20Rue%20Jean%20Giraudoux%2C%2075116%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745057880490!5m2!1sen!2s",
  },
  {
    id: 5,
    hotelName: "Hotel Dadou",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "10 rue Troyon - 75017 Paris",
    address: "10 rue Troyon - 75017 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://www.dadou.paris/",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      hotelDadouFacilities1,
      hotelDadouFacilities2,
      hotelDadouFacilities3,
      hotelDadouFacilities4,
      hotelDadouFacilities5,
    ],
    rooms: [
      hotelDadouRooms1,
      hotelDadouRooms2,
      hotelDadouRooms3,
      hotelDadouRooms4,
      hotelDadouRooms5,
    ],
    slider: [
      hotelDadouSlider1,
      hotelDadouSlider2,
      hotelDadouSlider3,
      hotelDadouSlider4,
    ],
    category: "Apartments",
    price: 75.90,
    banner: hotelDadou,
    heroImage: hotelDadouHero,
    locationImage: hotelDadouLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d164.00474676347662!2d2.2958616!3d48.8758287!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66feb605c0ac9%3A0xeb3bbc232a500a7d!2s10%20Rue%20Troyon%2C%2075017%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745062556705!5m2!1sen!2s"
  },
  {
    id: 6,
    hotelName: "Hotel Keppler",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "10 rue Keppler 75116 Paris",
    address: "10 rue Keppler 75116 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://www.keppler.fr",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      hotelKepplerFacilities1,
      hotelKepplerFacilities2,
      hotelKepplerFacilities3,
      hotelKepplerFacilities4,
      hotelKepplerFacilities5,
    ],
    rooms: [
      hotelKepplerRooms1,
      hotelKepplerRooms2,
      hotelKepplerRooms3,
      hotelKepplerRooms4,
      hotelKepplerRooms5,
    ],
    slider: [
      hotelKepplerSlider1,
      hotelKepplerSlider2,
      hotelKepplerSlider3,
      hotelKepplerSlider4,
      hotelKepplerSlider5,
      hotelKepplerSlider6,
    ],
    category: "Apartments",
    price: 75.90,
    banner: hotelKeppler,
    heroImage: hotelKepplerHero,
    locationImage: hotelKepplerLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d328.04869469258165!2d2.2972199300767704!3d48.86984984020026!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fe9024b8bc5%3A0x5ba86a3e64e3bc91!2s10%20Rue%20Kepler%2C%2075116%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745062632133!5m2!1sen!2s"
  },
  {
    id: 7,
    hotelName: "Hotel Victor Hugo Kleber",
    hotelTag: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    location: "19, rue Copernic 75116 Paris",
    address: "19, rue Copernic 75116 Paris",
    details: "All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel. All our Deluxe rooms have big windows to help you take a broad view of the cityscape and nature. We offer bigger bed and every bathroom has bathtub and shower, which brings relaxation to you after a long day. Fast WIFI connection, satelite TV and international standard electric socket are standard throughout Hotel.",
    overviewDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    overviewDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    facilitiesDetails2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    facilitiesDetails3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru",
    roomDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    loactionDetails: "The hotel sits on the fringes of Chow Kit, Kuala Lumpur’s once-upon-a- time red-light district, for which it was named.",
    planes: "Kuala Lumpur International Airport is 60 kilometres from the hotel and transfers can be arranged for MYR75 each way; Subang Airport is 27 kilometres away – transfers to and from this hub cost MYR50 each way.",
    trains: "The Medan Tuanku stop on the city’s monorail is six minutes away by car, and under five minutes on foot.",
    automobiles: "You won’t need your own set of wheels if you’re staying in the city, but it’s\ worth downloading the Grab app before you arrive – Malaysia’s answer to Uber. If you do choose to drive yourself, valet parking is MYR3 an hour or MYR15 a day.",
    Worthgettingoutofbedfor1: "Salute the sunrise with yoga sessions, held Monday, Wednesday and Friday on the hotel’s rooftop terrace. Then, after a fortifying breakfast, book onto a bespoke walking tour and learn about Chow Kit’s history, food and culture.",
    Worthgettingoutofbedfor2: "Wander through historic Loke Mansion or take a guided walking tour of nearby Chow Kit Market, Kuala Lumpur’s biggest, and get the inside scoop on the sprawling mass of stalls that sell everything from fresh produce and fish to DVDs of questionable origin.",
    Worthgettingoutofbedfor3: "In the mood for a little retail therapy? Make your way to Bukit Bintang, also known as Starhill, and treasure hunt through the district’s bijoux boutiques and sizeable shopping centres, stop for snacks at the hawker-style eateries and get your caffeine fix at one of the many alfresco cafés. If you’re inspired by Malaysian design, spruce up your own space with handcrafted furniture from ",
    localRestaurants: "Wake up with a jolt of rich coffee and a fluffy baked treat at nearby Common Grind before starting your day's city adventures. Stop for lunch Kin Kin Chilli Pan Mee Shop — made famous by Momofuku's David Chang - and order bowls of spicy noodles. If it's a steak and carbs kind of night, look no further than Marble 8 Steak House for the city's finest cuts of Wagyu and Angus.",
    hotelURL: "https://victorhugohotel.com",
    hotelTags: [
      "Pick Up & Drop",
      "Parking Space",
      "Room Service",
      "Swimming Pool",
      "Fibre Internet",
      "Breakfast",
    ],
    facilities: [
      hotelVictorHugoKleberFacilities1,
      hotelVictorHugoKleberFacilities2,
      hotelVictorHugoKleberFacilities3,
      hotelVictorHugoKleberFacilities4,
    ],
    rooms: [
      hotelVictorHugoKleberRooms1,
      hotelVictorHugoKleberRooms2,
      hotelVictorHugoKleberRooms3,
      hotelVictorHugoKleberRooms4,
    ],
    slider: [
      hotelVictorHugoKleberSlider1,
      hotelVictorHugoKleberSlider2,
      hotelVictorHugoKleberSlider3,
      hotelVictorHugoKleberSlider4,
      hotelVictorHugoKleberSlider5,
    ],
    category: "Apartments",
    price: 75.90,
    banner: hotelVictorHugoKleber,
    heroImage: hotelVictorHugoKleberHero,
    locationImage: hotelVictorHugoKleberLocation,
    addressURL: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d328.05218881036984!2d2.2885809!3d48.8693169!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66ff02718f9eb%3A0xb78188fee5c964fb!2s19%20Rue%20Copernic%2C%2075116%20Paris%2C%20France!5e0!3m2!1sen!2s!4v1745062699714!5m2!1sen!2s"
  },
]